version: '3.1'

services:

  db:
    image: mariadb
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootuser
    ports:
      - 3306:3306
      - 33060:33060

  php:
    build: .
    restart: always
    ports:
      - 8000:80
    environment: 
      MYSQL_ROOT_PASSWORD: rootuser
      MYSQL_ROOT_USER: root
      MYSQL_DATABASE: phpdemo
      MYSQL_HOSTNAME: db