version: '3.1'

services:

  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootuser
      MYSQL_DATABASE: db_oo
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    ports:
      - 3306:3306
      - 33060:33060

  php:
    image: drpdishant/firstapp
    restart: always
    ports:
      - 8080:80