---
- hosts: all
  gather_facts: true
  connection: local
  tasks:
    
    - name: docker | Start db container
      docker_container:
        docker_host: tcp://0.0.0.0:2376
        name: db
        image: mariadb
        ports: 
          - '3307:3306'
        env: 
          MYSQL_ROOT_PASSWORD: rootuser
        state: started

    - name: docker | Start web container
      docker_container:
        docker_host: tcp://0.0.0.0:2376
        name: web
        image: drpdishant/firstapp
        ports: 
          - '8000:80'
        links:
          - db
        state: started